addSbtPlugin("org.scala-js"      % "sbt-scalajs"  % "0.6.26")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.1.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "2.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.7")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"  % "0.3.3")
